### ISSUE TITLE
Milestone 1.2.0 Bugs

### ISSUE THREAD

**Issue by aelsergeev** [veegres/ivory#179]
Check and fix all of this bugs before release:

- [ ] 1. warning is case sensitive
- [ ] 2. credentials don't reload page after new credential was added :check:
- [ ] 3. cluster password doesn't show that it is saved after choose
- [ ] 4. no option to remove cluster password in assign settings in initial attempt (after select you have X that can make it)
- [ ] 5. bloat logs show only half of information in initial opening, no auto scroll to latest
- [ ] 6. default port
- [ ] 7. refresh button doesn't refresh cluster on click :check:
- [ ] 8. no error when secret is not correct (welcome back window)
- [ ] 9. if delete folder of cert (perhaps and for compacttable) it won't fire an error that it cannot create file
- [ ] 10. drag and drop file doesn't work on chrome properly (firefox good)
- [ ] 11. autodetection when you select last instance manually sometimes returns to same instance (main cause and problem unknown)
- [ ] 12. add options to settings dissable reopen tab reloading
- [ ] 13. when cert changed and request is not successful we continue showing that everything ok
- [ ] 14. refactoring errors in proxy.go
